# Generated by Django 4.2.11 on 2024-08-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instancy',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
