# Generated by Django 4.2.11 on 2024-08-26 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_user_instancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalaiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balai_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pdam_balai',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='balai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account_app.balaimodel'),
        ),
    ]
