# Generated by Django 4.2.11 on 2024-08-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_balaimodel_user_balai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'SuperAdmin'), (2, 'Admin'), (3, 'Guest'), (4, 'QA')], default=1),
        ),
    ]
