# Generated by Django 4.2.11 on 2024-07-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
            ],
        ),
    ]
