# Generated by Django 4.2.11 on 2024-07-11 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0003_stationmodel_created_at_rawmessagemodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rawmessagemodel',
            table='pdam_raw_message',
        ),
        migrations.AlterModelTable(
            name='stationmodel',
            table='pdam_station',
        ),
    ]
