# Generated by Django 4.2.11 on 2024-07-14 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0004_alter_rawmessagemodel_table_alter_stationmodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmessagemodel',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
