# Generated by Django 4.2.11 on 2024-07-14 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0007_alter_rawmessagemodel_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rawmessagemodel',
            unique_together={('station', 'time')},
        ),
    ]
