# Generated by Django 4.2.11 on 2024-07-16 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0009_alter_stationmodel_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('CH1', models.FloatField(null=True)),
                ('CH2', models.FloatField(null=True)),
                ('CH3', models.FloatField(null=True)),
                ('CH4', models.FloatField(null=True)),
                ('CH5', models.FloatField(null=True)),
                ('CH6', models.FloatField(null=True)),
                ('modCH5', models.FloatField(null=True)),
                ('modCH6', models.FloatField(null=True)),
                ('temperature', models.FloatField(null=True)),
                ('battery', models.FloatField(null=True)),
                ('saved_data', models.IntegerField(null=True)),
                ('itter_flow', models.IntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdam_app.stationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CheckerDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secs_col', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('CH1', models.FloatField(null=True)),
                ('CH2', models.FloatField(null=True)),
                ('CH3', models.FloatField(null=True)),
                ('CH4', models.FloatField(null=True)),
                ('CH5', models.FloatField(null=True)),
                ('CH6', models.FloatField(null=True)),
                ('modCH5', models.FloatField(null=True)),
                ('modCH6', models.FloatField(null=True)),
                ('temperature', models.FloatField(null=True)),
                ('battery', models.FloatField(null=True)),
                ('saved_data', models.IntegerField(null=True)),
                ('itter_flow', models.IntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdam_app.stationmodel')),
            ],
        ),
    ]
