# Generated by Django 4.2.11 on 2024-07-16 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0010_sensordatamodel_checkerdatamodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkerdatamodel',
            unique_together={('station', 'date_time')},
        ),
        migrations.AlterUniqueTogether(
            name='sensordatamodel',
            unique_together={('station', 'date_time')},
        ),
    ]
