# Generated by Django 4.2.11 on 2024-07-16 02:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0011_alter_checkerdatamodel_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkerdatamodel',
            old_name='date_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='sensordatamodel',
            old_name='date_time',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='sensordatamodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sensordatamodel',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='checkerdatamodel',
            unique_together={('station', 'time')},
        ),
        migrations.AlterUniqueTogether(
            name='sensordatamodel',
            unique_together={('station', 'time')},
        ),
    ]
