# Generated by Django 4.2.11 on 2024-07-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0013_stationmodel_factor_cal_stationmodel_percent_cal_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModifiedRecord',
            new_name='ModifiedRecordModel',
        ),
    ]
