# Generated by Django 4.2.11 on 2024-07-19 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0015_alter_checkerdatamodel_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecordMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdam_app.stationmodel')),
            ],
            options={
                'db_table': 'pdam_maintenancerecord',
            },
        ),
    ]
