# Generated by Django 4.2.11 on 2024-07-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0017_rename_maintenancerecordmode_maintenancerecordmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationmodel',
            name='maintenance_status',
            field=models.BooleanField(default=False),
        ),
    ]
