# Generated by Django 4.2.11 on 2024-07-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0018_stationmodel_maintenance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecordmodel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
