# Generated by Django 4.2.11 on 2024-07-19 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0019_alter_maintenancerecordmodel_end_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='maintenancerecordmodel',
            table='pdam_maintenance_record',
        ),
        migrations.AlterModelTable(
            name='modifiedrecordmodel',
            table='pdam_modified_record',
        ),
    ]
