# Generated by Django 4.2.11 on 2024-07-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0021_alter_checkerdatamodel_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecordmodel',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
