# Generated by Django 4.2.11 on 2024-07-19 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0022_alter_maintenancerecordmodel_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=30)),
                ('sensor_icon', models.ImageField(blank=True, null=True, upload_to='sensor_icon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StationConfigurationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdam_app.stationmodel')),
            ],
        ),
    ]
