# Generated by Django 4.2.11 on 2024-07-19 03:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0023_sensortypemodel_stationconfigurationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_label', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='stationconfigurationmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stationconfigurationmodel',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stationconfigurationmodel',
            name='sensor_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pdam_app.sensortypemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stationconfigurationmodel',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pdam_app.channelmodel'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='stationconfigurationmodel',
            unique_together={('station', 'channel')},
        ),
    ]
