# Generated by Django 4.2.11 on 2024-07-19 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0024_channelmodel_stationconfigurationmodel_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationConfigurationRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdam_app.channelmodel')),
                ('sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdam_app.sensortypemodel')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdam_app.stationmodel')),
            ],
        ),
    ]
