# Generated by Django 4.2.11 on 2024-07-19 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0025_stationconfigurationrecordmodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stationconfigurationmodel',
            unique_together={('station', 'channel', 'sensor_type')},
        ),
    ]
