# Generated by Django 4.2.11 on 2024-07-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0027_alter_stationconfigurationmodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stationconfigurationmodel',
            unique_together={('station', 'channel', 'sensor_type')},
        ),
    ]
