# Generated by Django 4.2.11 on 2024-07-19 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0030_alter_stationconfigurationmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stationconfigurationmodel',
            name='unique_station_channel_sensor_type',
        ),
        migrations.AlterUniqueTogether(
            name='stationconfigurationmodel',
            unique_together={('station', 'channel', 'sensor_type')},
        ),
    ]
