# Generated by Django 4.2.11 on 2024-07-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0031_remove_stationconfigurationmodel_unique_station_channel_sensor_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stationconfigurationmodel',
            unique_together={('station', 'channel'), ('station', 'sensor_type')},
        ),
    ]
