# Generated by Django 4.2.11 on 2024-07-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0032_alter_stationconfigurationmodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmessagemodel',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
