# Generated by Django 4.2.11 on 2024-07-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0033_rawmessagemodel_topic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rawmessagemodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rawmessagemodel',
            name='status',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='rawmessagemodel',
            unique_together={('station', 'time', 'status')},
        ),
    ]
