# Generated by Django 4.2.11 on 2024-07-22 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0034_alter_rawmessagemodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkerdatamodel',
            unique_together={('station', 'time', 'status')},
        ),
        migrations.AlterUniqueTogether(
            name='sensordatamodel',
            unique_together={('station', 'time', 'status')},
        ),
    ]
