# Generated by Django 4.2.11 on 2024-07-23 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0036_alter_checkerdatamodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkerdatamodel',
            unique_together={('station', 'time'), ('station', 'secs_col')},
        ),
    ]
