# Generated by Django 4.2.11 on 2024-07-23 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0037_alter_checkerdatamodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkerdatamodel',
            unique_together={('station', 'time')},
        ),
    ]
