# Generated by Django 4.2.11 on 2024-07-23 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0039_sensordatareqmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='channelmodel',
            table='pdam_channel',
        ),
        migrations.AlterModelTable(
            name='sensordatareqmodel',
            table='pdam_sensor_data_req',
        ),
        migrations.AlterModelTable(
            name='sensortypemodel',
            table='pdam_sensor_type',
        ),
        migrations.AlterModelTable(
            name='stationconfigurationmodel',
            table='pdam_station_configuration',
        ),
        migrations.AlterModelTable(
            name='stationconfigurationrecordmodel',
            table='pdam_station_configuration_record',
        ),
    ]
