# Generated by Django 4.2.11 on 2024-07-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0040_alter_channelmodel_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationconfigurationrecordmodel',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='stationconfigurationrecordmodel',
            name='sensor_type',
        ),
        migrations.RemoveField(
            model_name='stationconfigurationrecordmodel',
            name='station',
        ),
        migrations.DeleteModel(
            name='StationConfigurationModel',
        ),
        migrations.DeleteModel(
            name='StationConfigurationRecordModel',
        ),
    ]
