# Generated by Django 4.2.11 on 2024-07-23 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0041_remove_stationconfigurationrecordmodel_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationConfigurationRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdam_app.channelmodel')),
                ('sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdam_app.sensortypemodel')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdam_app.stationmodel')),
            ],
            options={
                'db_table': 'pdam_station_configuration_record',
            },
        ),
        migrations.CreateModel(
            name='StationConfigurationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdam_app.channelmodel')),
                ('sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdam_app.sensortypemodel')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdam_app.stationmodel')),
            ],
            options={
                'db_table': 'pdam_station_configuration',
                'unique_together': {('station', 'channel'), ('station', 'sensor_type')},
            },
        ),
    ]
