# Generated by Django 4.2.11 on 2024-07-24 05:46

from django.db import migrations, models
import pdam_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0042_stationconfigurationrecordmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationmodel',
            name='percent_cal',
            field=models.FloatField(default=0, validators=[pdam_app.models.validate_positive]),
        ),
    ]
