# Generated by Django 4.2.11 on 2024-07-24 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0044_sensordatareqmodel_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sensordatareqmodel',
            unique_together={('station', 'time', 'sensor_type', 'channel', 'data')},
        ),
    ]
