# Generated by Django 4.2.11 on 2024-07-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0045_alter_sensordatareqmodel_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logger_ver', models.CharField(max_length=100)),
                ('max_channel', models.IntegerField()),
                ('max_analog', models.IntegerField()),
                ('max_digital', models.IntegerField()),
            ],
            options={
                'db_table': 'pdam_logger',
            },
        ),
    ]
