# Generated by Django 4.2.11 on 2024-07-27 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0046_loggermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoggerModel',
            new_name='LoggerTypeModel',
        ),
    ]
