# Generated by Django 4.2.11 on 2024-08-01 04:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0048_stationmodel_logger_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdSensorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('day', models.IntegerField()),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(default=datetime.datetime(2024, 8, 1, 4, 32, 0, 879386, tzinfo=datetime.timezone.utc))),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdam_app.stationmodel')),
            ],
        ),
    ]
