# Generated by Django 4.2.11 on 2024-08-01 04:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0049_thresholdsensormodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thresholdsensormodel',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
