# Generated by Django 4.2.11 on 2024-08-02 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0050_alter_thresholdsensormodel_modified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdam_app.stationmodel')),
            ],
            options={
                'db_table': 'pdam_telegram_notification',
            },
        ),
    ]
