# Generated by Django 4.2.11 on 2024-08-03 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0051_telegramnotificationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationconfigurationmodel',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_configurations', to='pdam_app.stationmodel'),
        ),
    ]
