# Generated by Django 4.2.11 on 2024-08-05 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdam_app', '0052_alter_stationconfigurationmodel_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationconfigurationmodel',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stationconfigurationmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='station'),
        ),
        migrations.AddField(
            model_name='stationconfigurationmodel',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='stationmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stationmodel',
            name='elevation',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stationmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='station'),
        ),
        migrations.AddField(
            model_name='stationmodel',
            name='observator_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stationmodel',
            name='observator_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=15, null=True, region=None),
        ),
        migrations.AddField(
            model_name='stationmodel',
            name='sn_logger',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stationmodel',
            name='sn_modem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
