# Generated by Django 4.2.11 on 2024-08-05 02:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0054_stationmodel_station_serial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationmodel',
            name='station_serial_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uid'),
        ),
    ]
