# Generated by Django 4.2.11 on 2024-08-05 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0055_alter_stationmodel_station_serial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordatamodel',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_data', to='pdam_app.stationmodel'),
        ),
    ]
