# Generated by Django 4.2.11 on 2024-08-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0056_alter_sensordatamodel_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensortypemodel',
            name='notation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
