# Generated by Django 4.2.11 on 2024-08-20 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0057_sensortypemodel_notation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rawmessagemodel',
            unique_together={('time', 'status', 'topic')},
        ),
        migrations.RemoveField(
            model_name='rawmessagemodel',
            name='station',
        ),
    ]
