# Generated by Django 4.2.11 on 2024-08-26 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_balaimodel_user_balai'),
        ('pdam_app', '0058_alter_rawmessagemodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationmodel',
            name='balai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account_app.balaimodel'),
        ),
        migrations.AlterField(
            model_name='loggertypemodel',
            name='logger_ver',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='loggertypemodel',
            name='max_analog',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='loggertypemodel',
            name='max_channel',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='loggertypemodel',
            name='max_digital',
            field=models.PositiveIntegerField(),
        ),
    ]
