# Generated by Django 4.2.11 on 2024-08-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0061_alter_thresholdsensormodel_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishthresholdmodel',
            name='day',
            field=models.PositiveIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]),
        ),
        migrations.AlterField(
            model_name='thresholdsensormodel',
            name='day',
            field=models.PositiveIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]),
        ),
        migrations.AlterModelTable(
            name='thresholdsensormodel',
            table='pdam_threshold_sensor',
        ),
    ]
