# Generated by Django 4.2.11 on 2024-08-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0062_alter_publishthresholdmodel_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationmodel',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='stationmodel',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
