# Generated by Django 4.2.11 on 2024-08-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0063_stationmodel_latitude_stationmodel_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishthresholdmodel',
            name='receive_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
