# Generated by Django 4.2.11 on 2024-09-03 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0064_alter_publishthresholdmodel_receive_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishResenddModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdam_app.stationmodel')),
            ],
            options={
                'db_table': 'pdam_publish_resend',
            },
        ),
    ]
