# Generated by Django 4.2.11 on 2024-09-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0065_publishresenddmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublishResenddModel',
            new_name='PublishResendModel',
        ),
    ]
