# Generated by Django 4.2.11 on 2024-09-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0066_rename_publishresenddmodel_publishresendmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishresendmodel',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
