# Generated by Django 4.2.11 on 2024-09-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0067_publishresendmodel_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramnotificationmodel',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramnotificationmodel',
            name='notif_type',
            field=models.PositiveBigIntegerField(choices=[(1, 'Threshold'), (2, 'Missing')], default=1),
            preserve_default=False,
        ),
    ]
