# Generated by Django 4.2.11 on 2024-09-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0068_telegramnotificationmodel_is_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationmodel',
            name='capacity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stationmodel',
            name='interzone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stationmodel',
            name='max_flow',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stationmodel',
            name='nameplate_head',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stationmodel',
            name='pipe_diameter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stationmodel',
            name='sum_operation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
