# Generated by Django 4.2.11 on 2024-09-09 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdam_app', '0069_stationmodel_capacity_stationmodel_interzone_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sensordatamodel',
            unique_together={('station', 'time', 'status')},
        ),
        migrations.AlterUniqueTogether(
            name='sensordatareqmodel',
            unique_together={('station', 'time', 'sensor_type', 'channel', 'data', 'status')},
        ),
    ]
