--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: notify_delete(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.notify_delete() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    PERFORM pg_notify('channel_collect_change', 'DELETE');
    RETURN OLD;
END;
$$;


ALTER FUNCTION public.notify_delete() OWNER TO postgres;

--
-- Name: notify_insert(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.notify_insert() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    PERFORM pg_notify('channel_collect_change', 'INSERT');
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.notify_insert() OWNER TO postgres;

--
-- Name: notify_update(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.notify_update() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    PERFORM pg_notify('channel_collect_change', 'UPDATE');
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.notify_update() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: pdam_channel; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pdam_channel (
    id bigint NOT NULL,
    channel_label character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.pdam_channel OWNER TO postgres;

--
-- Name: pdam_app_channelmodel_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pdam_channel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pdam_app_channelmodel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pdam_checker_data; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pdam_checker_data (
    id bigint NOT NULL,
    secs_col integer NOT NULL,
    "time" timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    "CH1" double precision,
    "CH2" double precision,
    "CH3" double precision,
    "CH4" double precision,
    "CH5" double precision,
    "CH6" double precision,
    "modCH5" double precision,
    "modCH6" double precision,
    temperature double precision,
    battery double precision,
    saved_data integer,
    itter_flow integer,
    status integer,
    station_id bigint
);


ALTER TABLE public.pdam_checker_data OWNER TO postgres;

--
-- Name: pdam_app_checkerdatamodel_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pdam_checker_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pdam_app_checkerdatamodel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pdam_modified_record; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pdam_modified_record (
    id bigint NOT NULL,
    percent_cal double precision NOT NULL,
    factor_cal boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expired_at timestamp with time zone,
    station_id bigint NOT NULL
);


ALTER TABLE public.pdam_modified_record OWNER TO postgres;

--
-- Name: pdam_app_modifiedrecord_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pdam_modified_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pdam_app_modifiedrecord_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pdam_raw_message; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pdam_raw_message (
    id bigint NOT NULL,
    message character varying(200) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    station_id bigint NOT NULL,
    "time" timestamp with time zone NOT NULL,
    topic character varying(100),
    status integer NOT NULL
);


ALTER TABLE public.pdam_raw_message OWNER TO postgres;

--
-- Name: pdam_app_rawmessagemodel_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pdam_raw_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pdam_app_rawmessagemodel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pdam_sensor_data_req; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pdam_sensor_data_req (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    "time" timestamp with time zone NOT NULL,
    data double precision NOT NULL,
    iteration integer NOT NULL,
    channel_id bigint,
    sensor_type_id bigint,
    station_id bigint,
    status integer NOT NULL,
    CONSTRAINT pdam_sensor_data_req_status_check CHECK ((status >= 0))
);


ALTER TABLE public.pdam_sensor_data_req OWNER TO postgres;

--
-- Name: pdam_app_sensor_data_req_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pdam_sensor_data_req ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pdam_app_sensor_data_req_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pdam_sensor_data; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pdam_sensor_data (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    "CH1" double precision,
    "CH2" double precision,
    "CH3" double precision,
    "CH4" double precision,
    "CH5" double precision,
    "CH6" double precision,
    "modCH5" double precision,
    "modCH6" double precision,
    temperature double precision,
    battery double precision,
    saved_data integer,
    itter_flow integer,
    status integer,
    station_id bigint,
    "time" timestamp with time zone NOT NULL
);


ALTER TABLE public.pdam_sensor_data OWNER TO postgres;

--
-- Name: pdam_app_sensordatamodel_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pdam_sensor_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pdam_app_sensordatamodel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pdam_sensor_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pdam_sensor_type (
    id bigint NOT NULL,
    sensor_name character varying(30) NOT NULL,
    sensor_icon character varying(100),
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.pdam_sensor_type OWNER TO postgres;

--
-- Name: pdam_app_sensortypemodel_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pdam_sensor_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pdam_app_sensortypemodel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pdam_station; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pdam_station (
    id bigint NOT NULL,
    station_name character varying(100) NOT NULL,
    location character varying(100),
    topic character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    factor_cal boolean NOT NULL,
    percent_cal double precision NOT NULL,
    maintenance_status boolean NOT NULL,
    logger_type_id bigint NOT NULL
);


ALTER TABLE public.pdam_station OWNER TO postgres;

--
-- Name: pdam_app_stationmodel_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pdam_station ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pdam_app_stationmodel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pdam_app_thresholdsensormodel; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pdam_app_thresholdsensormodel (
    id bigint NOT NULL,
    hour integer NOT NULL,
    minute integer NOT NULL,
    day integer NOT NULL,
    min double precision NOT NULL,
    max double precision NOT NULL,
    created_at timestamp with time zone NOT NULL,
    modified_at timestamp with time zone NOT NULL,
    station_id bigint NOT NULL
);


ALTER TABLE public.pdam_app_thresholdsensormodel OWNER TO postgres;

--
-- Name: pdam_app_thresholdsensormodel_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pdam_app_thresholdsensormodel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pdam_app_thresholdsensormodel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pdam_logger; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pdam_logger (
    id bigint NOT NULL,
    logger_ver character varying(100) NOT NULL,
    max_channel integer NOT NULL,
    max_analog integer NOT NULL,
    max_digital integer NOT NULL
);


ALTER TABLE public.pdam_logger OWNER TO postgres;

--
-- Name: pdam_logger_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pdam_logger ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pdam_logger_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pdam_maintenance_record; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pdam_maintenance_record (
    id bigint NOT NULL,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone,
    station_id bigint NOT NULL
);


ALTER TABLE public.pdam_maintenance_record OWNER TO postgres;

--
-- Name: pdam_maintenancerecord_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pdam_maintenance_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pdam_maintenancerecord_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pdam_station_configuration; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pdam_station_configuration (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    modified_at timestamp with time zone NOT NULL,
    channel_id bigint NOT NULL,
    sensor_type_id bigint NOT NULL,
    station_id bigint NOT NULL
);


ALTER TABLE public.pdam_station_configuration OWNER TO postgres;

--
-- Name: pdam_station_configuration_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pdam_station_configuration ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pdam_station_configuration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pdam_station_configuration_record; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pdam_station_configuration_record (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    end_date timestamp with time zone,
    channel_id bigint NOT NULL,
    sensor_type_id bigint NOT NULL,
    station_id bigint NOT NULL
);


ALTER TABLE public.pdam_station_configuration_record OWNER TO postgres;

--
-- Name: pdam_station_configuration_record_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pdam_station_configuration_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pdam_station_configuration_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pdam_telegram_notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pdam_telegram_notification (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    station_id bigint
);


ALTER TABLE public.pdam_telegram_notification OWNER TO postgres;

--
-- Name: pdam_telegram_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pdam_telegram_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pdam_telegram_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: pdam_channel pdam_app_channelmodel_channel_label_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_channel
    ADD CONSTRAINT pdam_app_channelmodel_channel_label_key UNIQUE (channel_label);


--
-- Name: pdam_channel pdam_app_channelmodel_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_channel
    ADD CONSTRAINT pdam_app_channelmodel_pkey PRIMARY KEY (id);


--
-- Name: pdam_checker_data pdam_app_checkerdatamodel_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_checker_data
    ADD CONSTRAINT pdam_app_checkerdatamodel_pkey PRIMARY KEY (id);


--
-- Name: pdam_modified_record pdam_app_modifiedrecord_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_modified_record
    ADD CONSTRAINT pdam_app_modifiedrecord_pkey PRIMARY KEY (id);


--
-- Name: pdam_raw_message pdam_app_rawmessagemodel_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_raw_message
    ADD CONSTRAINT pdam_app_rawmessagemodel_pkey PRIMARY KEY (id);


--
-- Name: pdam_sensor_data_req pdam_app_sensor_data_req_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_sensor_data_req
    ADD CONSTRAINT pdam_app_sensor_data_req_pkey PRIMARY KEY (id);


--
-- Name: pdam_sensor_data pdam_app_sensordatamodel_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_sensor_data
    ADD CONSTRAINT pdam_app_sensordatamodel_pkey PRIMARY KEY (id);


--
-- Name: pdam_sensor_type pdam_app_sensortypemodel_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_sensor_type
    ADD CONSTRAINT pdam_app_sensortypemodel_pkey PRIMARY KEY (id);


--
-- Name: pdam_station pdam_app_stationmodel_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_station
    ADD CONSTRAINT pdam_app_stationmodel_pkey PRIMARY KEY (id);


--
-- Name: pdam_app_thresholdsensormodel pdam_app_thresholdsensormodel_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_app_thresholdsensormodel
    ADD CONSTRAINT pdam_app_thresholdsensormodel_pkey PRIMARY KEY (id);


--
-- Name: pdam_checker_data pdam_checker_data_station_id_time_4664b169_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_checker_data
    ADD CONSTRAINT pdam_checker_data_station_id_time_4664b169_uniq UNIQUE (station_id, "time");


--
-- Name: pdam_logger pdam_logger_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_logger
    ADD CONSTRAINT pdam_logger_pkey PRIMARY KEY (id);


--
-- Name: pdam_maintenance_record pdam_maintenancerecord_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_maintenance_record
    ADD CONSTRAINT pdam_maintenancerecord_pkey PRIMARY KEY (id);


--
-- Name: pdam_raw_message pdam_raw_message_station_id_time_status_0942b5a1_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_raw_message
    ADD CONSTRAINT pdam_raw_message_station_id_time_status_0942b5a1_uniq UNIQUE (station_id, "time", status);


--
-- Name: pdam_sensor_data_req pdam_sensor_data_req_station_id_time_sensor_t_3eaa8613_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_sensor_data_req
    ADD CONSTRAINT pdam_sensor_data_req_station_id_time_sensor_t_3eaa8613_uniq UNIQUE (station_id, "time", sensor_type_id, channel_id, data);


--
-- Name: pdam_sensor_data pdam_sensor_data_station_id_time_dcf397d4_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_sensor_data
    ADD CONSTRAINT pdam_sensor_data_station_id_time_dcf397d4_uniq UNIQUE (station_id, "time");


--
-- Name: pdam_station_configuration pdam_station_configurati_station_id_sensor_type_i_82822e35_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_station_configuration
    ADD CONSTRAINT pdam_station_configurati_station_id_sensor_type_i_82822e35_uniq UNIQUE (station_id, sensor_type_id);


--
-- Name: pdam_station_configuration pdam_station_configuration_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_station_configuration
    ADD CONSTRAINT pdam_station_configuration_pkey PRIMARY KEY (id);


--
-- Name: pdam_station_configuration_record pdam_station_configuration_record_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_station_configuration_record
    ADD CONSTRAINT pdam_station_configuration_record_pkey PRIMARY KEY (id);


--
-- Name: pdam_station_configuration pdam_station_configuration_station_id_channel_id_94457da1_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_station_configuration
    ADD CONSTRAINT pdam_station_configuration_station_id_channel_id_94457da1_uniq UNIQUE (station_id, channel_id);


--
-- Name: pdam_station pdam_station_topic_717bd097_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_station
    ADD CONSTRAINT pdam_station_topic_717bd097_uniq UNIQUE (topic);


--
-- Name: pdam_telegram_notification pdam_telegram_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_telegram_notification
    ADD CONSTRAINT pdam_telegram_notification_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: pdam_app_channelmodel_channel_label_ae168702_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pdam_app_channelmodel_channel_label_ae168702_like ON public.pdam_channel USING btree (channel_label varchar_pattern_ops);


--
-- Name: pdam_app_checkerdatamodel_station_id_4999184e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pdam_app_checkerdatamodel_station_id_4999184e ON public.pdam_checker_data USING btree (station_id);


--
-- Name: pdam_app_modifiedrecord_station_id_b2de5075; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pdam_app_modifiedrecord_station_id_b2de5075 ON public.pdam_modified_record USING btree (station_id);


--
-- Name: pdam_app_rawmessagemodel_station_id_4306d67f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pdam_app_rawmessagemodel_station_id_4306d67f ON public.pdam_raw_message USING btree (station_id);


--
-- Name: pdam_app_sensor_data_req_channel_id_713cd031; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pdam_app_sensor_data_req_channel_id_713cd031 ON public.pdam_sensor_data_req USING btree (channel_id);


--
-- Name: pdam_app_sensor_data_req_sensor_type_id_b0775a6c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pdam_app_sensor_data_req_sensor_type_id_b0775a6c ON public.pdam_sensor_data_req USING btree (sensor_type_id);


--
-- Name: pdam_app_sensor_data_req_station_id_81a070b5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pdam_app_sensor_data_req_station_id_81a070b5 ON public.pdam_sensor_data_req USING btree (station_id);


--
-- Name: pdam_app_sensordatamodel_station_id_0d2334e7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pdam_app_sensordatamodel_station_id_0d2334e7 ON public.pdam_sensor_data USING btree (station_id);


--
-- Name: pdam_app_thresholdsensormodel_station_id_e1b2d91c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pdam_app_thresholdsensormodel_station_id_e1b2d91c ON public.pdam_app_thresholdsensormodel USING btree (station_id);


--
-- Name: pdam_maintenancerecord_station_id_a275cd3e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pdam_maintenancerecord_station_id_a275cd3e ON public.pdam_maintenance_record USING btree (station_id);


--
-- Name: pdam_station_configuration_channel_id_14fcd748; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pdam_station_configuration_channel_id_14fcd748 ON public.pdam_station_configuration USING btree (channel_id);


--
-- Name: pdam_station_configuration_record_channel_id_5f6c120f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pdam_station_configuration_record_channel_id_5f6c120f ON public.pdam_station_configuration_record USING btree (channel_id);


--
-- Name: pdam_station_configuration_record_sensor_type_id_cb978b47; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pdam_station_configuration_record_sensor_type_id_cb978b47 ON public.pdam_station_configuration_record USING btree (sensor_type_id);


--
-- Name: pdam_station_configuration_record_station_id_b1cab49c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pdam_station_configuration_record_station_id_b1cab49c ON public.pdam_station_configuration_record USING btree (station_id);


--
-- Name: pdam_station_configuration_sensor_type_id_ebc9fa28; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pdam_station_configuration_sensor_type_id_ebc9fa28 ON public.pdam_station_configuration USING btree (sensor_type_id);


--
-- Name: pdam_station_configuration_station_id_13c26d8a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pdam_station_configuration_station_id_13c26d8a ON public.pdam_station_configuration USING btree (station_id);


--
-- Name: pdam_station_logger_type_id_0a5d7be3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pdam_station_logger_type_id_0a5d7be3 ON public.pdam_station USING btree (logger_type_id);


--
-- Name: pdam_station_topic_717bd097_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pdam_station_topic_717bd097_like ON public.pdam_station USING btree (topic varchar_pattern_ops);


--
-- Name: pdam_telegram_notification_station_id_ce5b3358; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pdam_telegram_notification_station_id_ce5b3358 ON public.pdam_telegram_notification USING btree (station_id);


--
-- Name: pdam_raw_message delete_trigger_pdam_raw_message; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER delete_trigger_pdam_raw_message AFTER DELETE ON public.pdam_raw_message FOR EACH ROW EXECUTE FUNCTION public.notify_delete();


--
-- Name: pdam_station delete_trigger_pdam_station; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER delete_trigger_pdam_station AFTER DELETE ON public.pdam_station FOR EACH ROW EXECUTE FUNCTION public.notify_delete();


--
-- Name: pdam_raw_message insert_trigger_pdam_raw_message; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER insert_trigger_pdam_raw_message AFTER INSERT ON public.pdam_raw_message FOR EACH ROW EXECUTE FUNCTION public.notify_insert();


--
-- Name: pdam_station insert_trigger_pdam_station; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER insert_trigger_pdam_station AFTER INSERT ON public.pdam_station FOR EACH ROW EXECUTE FUNCTION public.notify_insert();


--
-- Name: pdam_raw_message update_trigger_pdam_raw_message; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_trigger_pdam_raw_message AFTER UPDATE ON public.pdam_raw_message FOR EACH ROW EXECUTE FUNCTION public.notify_update();


--
-- Name: pdam_station update_trigger_pdam_station; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_trigger_pdam_station AFTER UPDATE ON public.pdam_station FOR EACH ROW EXECUTE FUNCTION public.notify_update();


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pdam_checker_data pdam_app_checkerdata_station_id_4999184e_fk_pdam_stat; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_checker_data
    ADD CONSTRAINT pdam_app_checkerdata_station_id_4999184e_fk_pdam_stat FOREIGN KEY (station_id) REFERENCES public.pdam_station(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pdam_modified_record pdam_app_modifiedrecord_station_id_b2de5075_fk_pdam_station_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_modified_record
    ADD CONSTRAINT pdam_app_modifiedrecord_station_id_b2de5075_fk_pdam_station_id FOREIGN KEY (station_id) REFERENCES public.pdam_station(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pdam_raw_message pdam_app_rawmessagem_station_id_4306d67f_fk_pdam_app_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_raw_message
    ADD CONSTRAINT pdam_app_rawmessagem_station_id_4306d67f_fk_pdam_app_ FOREIGN KEY (station_id) REFERENCES public.pdam_station(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pdam_sensor_data_req pdam_app_sensor_data_channel_id_713cd031_fk_pdam_app_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_sensor_data_req
    ADD CONSTRAINT pdam_app_sensor_data_channel_id_713cd031_fk_pdam_app_ FOREIGN KEY (channel_id) REFERENCES public.pdam_channel(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pdam_sensor_data_req pdam_app_sensor_data_req_station_id_81a070b5_fk_pdam_station_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_sensor_data_req
    ADD CONSTRAINT pdam_app_sensor_data_req_station_id_81a070b5_fk_pdam_station_id FOREIGN KEY (station_id) REFERENCES public.pdam_station(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pdam_sensor_data_req pdam_app_sensor_data_sensor_type_id_b0775a6c_fk_pdam_app_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_sensor_data_req
    ADD CONSTRAINT pdam_app_sensor_data_sensor_type_id_b0775a6c_fk_pdam_app_ FOREIGN KEY (sensor_type_id) REFERENCES public.pdam_sensor_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pdam_sensor_data pdam_app_sensordatamodel_station_id_0d2334e7_fk_pdam_station_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_sensor_data
    ADD CONSTRAINT pdam_app_sensordatamodel_station_id_0d2334e7_fk_pdam_station_id FOREIGN KEY (station_id) REFERENCES public.pdam_station(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pdam_app_thresholdsensormodel pdam_app_thresholdse_station_id_e1b2d91c_fk_pdam_stat; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_app_thresholdsensormodel
    ADD CONSTRAINT pdam_app_thresholdse_station_id_e1b2d91c_fk_pdam_stat FOREIGN KEY (station_id) REFERENCES public.pdam_station(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pdam_maintenance_record pdam_maintenancerecord_station_id_a275cd3e_fk_pdam_station_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_maintenance_record
    ADD CONSTRAINT pdam_maintenancerecord_station_id_a275cd3e_fk_pdam_station_id FOREIGN KEY (station_id) REFERENCES public.pdam_station(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pdam_station_configuration pdam_station_configu_channel_id_14fcd748_fk_pdam_chan; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_station_configuration
    ADD CONSTRAINT pdam_station_configu_channel_id_14fcd748_fk_pdam_chan FOREIGN KEY (channel_id) REFERENCES public.pdam_channel(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pdam_station_configuration_record pdam_station_configu_channel_id_5f6c120f_fk_pdam_chan; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_station_configuration_record
    ADD CONSTRAINT pdam_station_configu_channel_id_5f6c120f_fk_pdam_chan FOREIGN KEY (channel_id) REFERENCES public.pdam_channel(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pdam_station_configuration_record pdam_station_configu_sensor_type_id_cb978b47_fk_pdam_sens; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_station_configuration_record
    ADD CONSTRAINT pdam_station_configu_sensor_type_id_cb978b47_fk_pdam_sens FOREIGN KEY (sensor_type_id) REFERENCES public.pdam_sensor_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pdam_station_configuration pdam_station_configu_sensor_type_id_ebc9fa28_fk_pdam_sens; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_station_configuration
    ADD CONSTRAINT pdam_station_configu_sensor_type_id_ebc9fa28_fk_pdam_sens FOREIGN KEY (sensor_type_id) REFERENCES public.pdam_sensor_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pdam_station_configuration pdam_station_configu_station_id_13c26d8a_fk_pdam_stat; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_station_configuration
    ADD CONSTRAINT pdam_station_configu_station_id_13c26d8a_fk_pdam_stat FOREIGN KEY (station_id) REFERENCES public.pdam_station(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pdam_station_configuration_record pdam_station_configu_station_id_b1cab49c_fk_pdam_stat; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_station_configuration_record
    ADD CONSTRAINT pdam_station_configu_station_id_b1cab49c_fk_pdam_stat FOREIGN KEY (station_id) REFERENCES public.pdam_station(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pdam_station pdam_station_logger_type_id_0a5d7be3_fk_pdam_logger_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_station
    ADD CONSTRAINT pdam_station_logger_type_id_0a5d7be3_fk_pdam_logger_id FOREIGN KEY (logger_type_id) REFERENCES public.pdam_logger(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pdam_telegram_notification pdam_telegram_notifi_station_id_ce5b3358_fk_pdam_stat; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pdam_telegram_notification
    ADD CONSTRAINT pdam_telegram_notifi_station_id_ce5b3358_fk_pdam_stat FOREIGN KEY (station_id) REFERENCES public.pdam_station(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

